[build]
  publish = "."
  command = "echo 'No build step needed'"

# Cache headers for static assets
[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

# Redirect rules for better SEO
[[redirects]]
  from = "/designpage"
  to = "/designpage.html"
  status = 301

[[redirects]]
  from = "/design"
  to = "/designpage.html"
  status = 301

# Block access to sensitive pages
[[headers]]
  for = "/checkout.html"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow, noarchive, nosnippet"

[[headers]]
  for = "/success.html"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow, noarchive, nosnippet"

[[headers]]
  for = "/policies.html"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow, noarchive, nosnippet"

[[headers]]
  for = "/test-order-flow.html"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow, noarchive, nosnippet"

# Block access to API directory
[[headers]]
  for = "/api/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"

# Block access to image directories
[[headers]]
  for = "/images/primarycolors/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"

[[headers]]
  for = "/images/secondarycolors/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"

[[headers]]
  for = "/images/motiv/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"

# Redirect direct access to checkout (only allow from your domain)
[[redirects]]
  from = "/checkout.html"
  to = "/index.html"
  status = 302
  conditions = {Referer = "!https://nordkaliber.store/*"}