[build]
  publish = "."
  functions = "api"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Remove the catch-all redirect that was preventing direct access to HTML files
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200

[functions]
  node_bundler = "esbuild" 